version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: easy_liturgy
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
volumes:
  db-data: